import { defaultLaborType } from "./calculations";
import type { EmployeeCategory, FinishedProduct } from "./types";

export const INITIAL_PRODUCTS: FinishedProduct[] = [
  {
    id: "pf-1",
    name: "Huile d'olive extra vierge 1L",
    sku: "HO-EV-1L",
    unit: "bouteille",
    water: 0.12,
    electricity: 0.35,
    directLabor: 0.85,
    additives: 0.05,
    rawMaterials: 4.2,
    other: 0.18,
    monthlyVolume: 12000,
  },
  {
    id: "pf-2",
    name: "Confiture figue 350g",
    sku: "CF-FIG-350",
    unit: "pot",
    water: 0.08,
    electricity: 0.22,
    directLabor: 0.55,
    additives: 0.12,
    rawMaterials: 1.85,
    other: 0.1,
    monthlyVolume: 8500,
  },
  {
    id: "pf-3",
    name: "Harissa artisanale 500g",
    sku: "HA-ART-500",
    unit: "pot",
    water: 0.05,
    electricity: 0.18,
    directLabor: 0.42,
    additives: 0.08,
    rawMaterials: 1.2,
    other: 0.09,
    monthlyVolume: 15000,
  },
];

export const INITIAL_EMPLOYEES: EmployeeCategory[] = [
  {
    id: "emp-1",
    poste: "Opérateurs ligne",
    department: "production",
    laborType: defaultLaborType("production"),
    headcount: 24,
    netSalaryDesired: 950,
  },
  {
    id: "emp-2",
    poste: "Techniciens maintenance",
    department: "production",
    laborType: defaultLaborType("production"),
    headcount: 4,
    netSalaryDesired: 1400,
  },
  {
    id: "emp-3",
    poste: "Agents conditionnement",
    department: "conditionnement",
    laborType: defaultLaborType("conditionnement"),
    headcount: 12,
    netSalaryDesired: 820,
  },
  {
    id: "emp-4",
    poste: "Qualité & laboratoire",
    department: "support",
    laborType: defaultLaborType("support"),
    headcount: 3,
    netSalaryDesired: 1650,
  },
  {
    id: "emp-5",
    poste: "Comptabilité & RH",
    department: "administration",
    laborType: defaultLaborType("administration"),
    headcount: 2,
    netSalaryDesired: 1800,
  },
  {
    id: "emp-6",
    poste: "Direction générale",
    department: "direction",
    laborType: defaultLaborType("direction"),
    headcount: 2,
    netSalaryDesired: 4500,
  },
];
